video:
  source: "0"
  target_fps: 20
  frame_size: [640, 480]
  max_queue: 5
models:
  face_detector: "deepface-retinaface"
  liveness:
    enable: true
    blink_window: 15
    mouth_open_thresh: 0.5
    head_pose_max_deg: 20
  deepfake:
    enable: true
    hub_repo: "REPLACE_WITH_PYTORCH_HUB_REPO"
    model_name: "REPLACE_WITH_MODEL"
fusion:
  temporal_window: 25
  method: "weighted_sum"
  weights: { liveness: 0.5, deepfake: 0.5 }
  thresholds: { real: 0.3, uncertain: 0.5, fake: 0.7 }
api:
  host: "0.0.0.0"
  port: 8000
telemetry:
  prometheus_port: 9100
